### ISSUE TITLE
README-windows.md

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-job#1]
rename 

https://github.com/cloudmesh/cloudmesh-job/blob/master/Job_Demo_Windows.md

to README-windows.md

and update pointers to the task list document

**Comment by kpimparkar** [comment]
Professor Gregor has renamed the file and corrected the link in the [list_of_tasks.md](https://github.com/cloudmesh/cloudmesh-job/blob/main/list_of_tasks.md).
Closing the task as it is complete.
