### ISSUE TITLE
markdown toc

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-job#11]
identify if there is a prg that can update an existing TOC

I used 

markdown-toc -t github README-windows.md

but have to remove the toc to regenerate

https://pypi.org/project/markdown-toc/

Maybe there is a better tool, I like the TOC and have done it differently, but i like that we can directly do it in the main document.

Also this tool does indentation wrong it uses tabs but should indnt bellow the items when doing subitems.

**Comment by laszewsk** [comment]
there is also https://pypi.org/project/md-toc/ but i have not tried this. there may be others

**Comment by kpimparkar** [comment]
I have used the following webpage in the past for TOC generation:
https://ecotrust-canada.github.io/markdown-toc/

This one has a simple interface but the markdown used in output doesn't exactly match with what is currently used in README-windows.md

**Comment by laszewsk** [comment]
I wonder if we can find a command tool instead of a web tool that can be repeatedly executed and updates the TOC. I like your idea with the TOC. I will now look at md-toc

**Comment by laszewsk** [comment]
This works great:

md_toc -p github  a.md

we just have to put a marker  in the location for the TOC
We can than use a Makefile to update the TOC when we make structural changes.

I include that next

**Comment by laszewsk** [comment]
make toc

creates now automatically the table of content and overwrites what was there before.
