### ISSUE TITLE
activate ENV3

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-job#12]
what is the mechanism in windows to automatically activate ENV3 whenever you start a new CMD.exe?

e.g now you have tp say this

C:\>ENV3\Scripts\activate.bat

In Linux we put it simply in the .bashrc file is there something similar?

**Comment by laszewsk** [comment]
also we may recommend simply to use gitbash as alternate so it looks just like linux?

**Comment by kpimparkar** [comment]
- In Windows, we have to create a batch file to achieve this. The batch file will contain:
`cmd.exe /K C:\ENV4\Scripts\activate.bat`
- Using gitbash would be the best approach in this case

I added a note in the main README.md and README-Windows.md suggesting use of gitbash. 
Please convey if any further action is needed. Thank you!

**Comment by laszewsk** [comment]
I have made supstantial cahnges and everything is now switched to $. Can you check if your .bat tip is still in there.

**Comment by laszewsk** [comment]
filename is now README-example.md

**Comment by kpimparkar** [comment]
The note to use .bat file in added in README-example.md
