### ISSUE TITLE
test ./ouput dir

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-job#2]
Can you mod tests so that txt files go into output dir

./output/test_01_job_cli_results.txt
./output/test_02_job_cli_results.txt

**Comment by kpimparkar** [comment]
- Existing results are moved to `tests/output` directory
- Sample `pytest` commands provided in `test_01_job_cli.py` and `test_02_job_api.py` are modified to use `tee` so that results can be redirected to `tests/output` directory

**Comment by kpimparkar** [comment]
Closing this issue with above steps, please convey if any further modification is needed. Thank you!
