### ISSUE TITLE
verify job bundle and path names with / on Windows

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-job#6]
- [x] (gregor) add cms + cloudmesh-job to cloudmesh installer
- [x] (gregor) make release of cloudmesh installer
- [x] (gregor) update install instructions to 
  
       ```
       pip install cloudmesh-installer
       cloudmesh-installer install job
       ```
- [x] (Ketan) A test on windows is required with new bundle and documentation. That test needs to verify if on windows we can use "/" and not "\" in the path this simplifies documentation significantly. path_expand should be used as I think this will work with it

**Comment by laszewsk** [comment]
a job bundle was added and documentation was changed.
A test on windows is required with new bundle and documentation
Also the filenames should use "/" and not "\" when we document but it must be possible to run this with "/" on windows also. path_expand should be bale to do this automatically we need to check if it is used

**Comment by kpimparkar** [comment]
The latest installation steps work perfectly. Use of "/" and "~" in command arguments work fine as well:

```
(ENV5) C:\>cms job set '~/.cloudmesh/job/a.yaml'
job set '~/.cloudmesh/job/a.yaml'
Jobset defined as a located at~\.cloudmesh\job\a.yaml
```
