### ISSUE TITLE
fix manual page in code and markdonwn file

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-job#7]
- [x] (Gregor) remove leading blanks from code block in readme. This is when I detected there are unmerged changes from master and i stopped doing it. It's easy in pycharm
- [x] (Gregor) README.md has been changed 
- [x] (Gregor) added bin/manaul-update.py which is now called with make readme
- [x] (Ketan) review README and remove redundancy if you detect there is.
- [x] (Ketan) make sure the manual page in job.py is up to date
- [x] (Ketan) the lines with the examples and defaults are too long, see if they can be mofed to next lien and this still works
- [x] (Ketan) check if the modified default works
- [x] (Ketan) check if the tests work
- [x] (Gregor) add tests tod README

**Comment by laszewsk** [comment]
looks like this is the next tasks before it gets more complex ;-)

**Comment by laszewsk** [comment]
I just made some minor cahnges in the command/job.py manual page.

So what I think we need to do is to have a little python program that replaces the text between 



...



and than it simply. writes the entire output of the manual page in that location when we call it with 

cms job help

similar to the toc. 

Than we integrate that into the Makefile also so when we change the man page in the py file we can easily update the README.
We than remove the duplicated stuff from the readme and make sure that we  document properly in teh code.
We should also add a 

See Also:
   URL to the example readme

**Comment by laszewsk** [comment]
can you work on the script.

**Comment by laszewsk** [comment]
```
manual = False
man = Shell.run("cms job help"
for line in man.splitlines():
   if "<!-- MANUAL -->" in line:
        manual = not manual
   if manual:
      print (man)
   else:
       pass
   if not manual:
       print(line)
```

**Comment by laszewsk** [comment]
you can also do a split on the MANUAL maker and just print, so this can be reduced in 3 lines

**Comment by laszewsk** [comment]
and then naturally focus on making sure the manual is up to date ;-)

**Comment by laszewsk** [comment]
I added the markers to the README.md

**Comment by kpimparkar** [comment]
Ok, I will start working on this script. 
Could you please also share some hint about the short and long help needed from `cms help`?

**Comment by laszewsk** [comment]
i have script almost done,. i check in what I have, some small cleanup in first and last lines , but other than that works pretty well

**Comment by laszewsk** [comment]
/bin/manual-update.py is now done was simpler than originally posted

**Comment by laszewsk** [comment]
./bin/make-update.py is done
it is calleble via 
make readme

**Comment by laszewsk** [comment]
updated your tasks. we are almost done with cloudmesh-job documentation ;-)

**Comment by kpimparkar** [comment]
Required corrections are done. README.md is regenerated using make to sync manual page between job.py and README.md

**Comment by laszewsk** [comment]
I improved. Job.py while keeping your previous defaults but removing some of the Ex. instead. I think its now fitting and we can leverage the defaults from docopts. Could you check quickly

Do we actually have a unit check for this? we do not have to check everything ...

but maybe something like 

cms set host=huliet
cms job --.....

**Comment by laszewsk** [comment]
I have improved the test by removing your hardcoded username with cms set variables. I also updated the usage on top. I think it would be good to add a section Tests and just put the 4 lines on how to check the test. The tee in the documentation is not needed.

**Comment by kpimparkar** [comment]
The tasks mentioned in this issue are complete.
