### ISSUE TITLE
Windows vs linux Documentation

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-job#9]
https://github.com/cloudmesh/cloudmesh-job/blob/master/Job_Demo_Windows.md#todo-some-other-thing-that-was-not-in-table

I had to remove table we do not do tables like this in markdown. Fix headline and add an explanation to section including parent two sections

**Comment by kpimparkar** [comment]
Suggested changes are done. The corrected document is available at:
https://github.com/cloudmesh/cloudmesh-job/blob/main/README-windows.md

**Comment by laszewsk** [comment]
Am I correct that there is no real difference between this on Linux, windows and macoOS other than the / in the path?

If so can you verify that if you give the path on the commandline in Windows like this works

"~/.cloudmesh/...."
and so forth

the reason being that we than can just use "$" and say on the top this can also be executed in cmd.exe while $ means also (ENV3) C:\>

So we would instead write 

(ENV3) $

**Comment by kpimparkar** [comment]
In the python code we have used path_expand, and we are using Linux style paths in the code. Hence, any argument to the "cms job" command uses Linux style paths even on Windows machines. For ex: 
`(ENV3) C:\>cms job set '~/.cloudmesh/job/spec.yaml'`

However, "~" and "$" don't work in Windows command prompt. 
```
(ENV4) C:\Study\IUMSDS\Fall2019\CloudComputing\cm>cd ~/.cloudmesh
The system cannot find the path specified.
```

Therefore, I think the commands remain unchanged for Linux/Windows or MacOS. Its just the command prompt behavior which differs.

Please convey if any further analysis is needed for this bug. Thank you!

**Comment by laszewsk** [comment]
I have changed the prompts to $ 
I have fixed the filename
I added the toc to make toc
